version: "3.8"
services:


  zeuscommerce_app:
    image: zeuscommerce
    container_name: zeus_commerce
    environment:
      MONGO_URI: mongodb://{url}:{port}/ZeusCommerce?replicaSet=zeusReplica
      Docker_Rabbit: {url}
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    ports:
      - 8080:8080
    volumes:
      - zeuscommerce-data:/app/data
    networks:
      - zeus-network
  hathorconsumer_app:
    image: hathorconsumer
    container_name: hathor_commerce
    depends_on:
      zeuscommerce_app:
        condition: service_started
    environment:
      MONGO_URI: mongodb://{yoururl},{replicaURL}/ZeusCommerce?replicaSet=zeusReplica
      Docker_Rabbit: { url }
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    ports:
      - 9000:9000
    networks:
      - zeus-network
    volumes:
      - hathorconsumer-data:/app/data

  khonsudelivery_app:
    image: khonsudelivery
    container_name: khonsu_delivery
    depends_on:
      zeuscommerce_app:
        condition: service_started
      hathorconsumer_app:
        condition: service_started
    environment:
      MONGO_URI: mongodb://{yoururl},{replicaURL}/ZeusCommerce?replicaSet=zeusReplica
      Docker_Rabbit: { url }
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    networks:
      - zeus-network
    ports:
      - 8888:8888
    volumes:
      - khonsudelivery-data:/app/data

volumes:
  zeuscommerce-data:
  hathorconsumer-data:
  khonsudelivery-data:
networks:
  zeus-network:
    driver: bridge
